version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 3000:3000
    container_name: sequence-api
    depends_on:
      - postgres
    networks:
      - api-postgres
      - ui-api
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sequence
    networks:
      - api-postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8000:8000"
    container_name: sequence-ui
    networks:
      - ui-api
    environment:
      PORT: 8000
      NEXT_PUBLIC_API_URL: http://0.0.0.0:3000
    expose:
      - 8000
networks:
  ui-api:
  api-postgres:
